controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
      - Joint_7
initial:  # Define initial robot poses.
#  - group: arm
#    pose: home

  []